#!/bin/bash
# First-boot setup of a Vault node, run once by cloud-init (runcmd).
#
# cloud-init has already written every file this needs (see write_files in
# modules/vault-node/main.tf): scripts, systemd units, and the Terraform-generated
# settings in /etc/vault-node/. This installs Vault, mounts the data volume, starts
# Vault, and then initialises it or restores it from the latest snapshot.

# node.env is generated by Terraform and only exists on the node.
# shellcheck disable=SC1091
set -euo pipefail
exec > >(tee -a /var/log/vault-bootstrap.log) 2>&1
set -a; . /etc/vault-node/node.env; set +a

# --- Snapshot schedule, first ----------------------------------------------------
# First on purpose, so no failure further down can skip it: if the bootstrap
# refuses or fails, a manual re-run must still leave a node that takes snapshots.
# Runs before Vault exists are harmless: the snapshot service won't start Vault
# (Requisite=), and the login only works once Vault holds real data.
systemctl daemon-reload   # pick up the units and drop-ins cloud-init wrote
systemctl enable --now vault-snapshot.timer vault-snapshot-on-stop.service

# --- Install (the OS-specific part) ------------------------------------------------
dnf install -y dnf-plugins-core shadow-utils jq   # shadow-utils: the vault RPM runs useradd
dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
dnf install -y "vault-$VAULT_VERSION"

# Our config replaces the RPM's (staged by cloud-init, which runs before the RPM
# exists; both files are %config(noreplace), so installing them now is clearest).
install -o vault -g vault -m 0640 /etc/vault-node/vault.hcl /etc/vault-node/vault.env /etc/vault.d/

# --- Data volume -----------------------------------------------------------------
# Raft data lives on its own EBS volume, so the node can be replaced (new AMI, new
# Vault version, other instance type) without losing it. Terraform attaches the
# volume after the instance starts, so wait for it. Format only if it's blank:
# a volume that already has a file system holds the data of a previous node.
echo "Waiting for data volume $DATA_DEVICE..."
for _ in $(seq 300); do [ -e "$DATA_DEVICE" ] && break; sleep 2; done
[ -e "$DATA_DEVICE" ] || { echo "ERROR: data volume never showed up" >&2; exit 1; }

if blkid "$DATA_DEVICE" >/dev/null; then
  echo "Data volume has a file system: reusing it."
else
  echo "Data volume is blank: formatting."
  mkfs.xfs -L vault-data "$DATA_DEVICE"
fi
echo 'LABEL=vault-data /opt/vault/data xfs defaults,nofail 0 2' >> /etc/fstab
systemctl daemon-reload
mount /opt/vault/data
chown -R vault:vault /opt/vault/data   # the vault uid can differ between nodes
chmod 750 /opt/vault/data

# --- Start -------------------------------------------------------------------------
systemctl daemon-reload   # pick up vault.service from the RPM
systemctl enable --now vault
/usr/local/bin/vault-bootstrap.sh
/usr/local/bin/vault-snapshot.sh bootstrap
