#!/bin/bash
# usage: vault-snapshot.sh [reason]
# Save a Raft snapshot and upload it to s3://$SNAPSHOT_BUCKET/$SNAPSHOT_OBJECT_KEY.
#
# Authenticates with Vault's AWS auth method as this node's IAM role, which only
# grants reading sys/storage/raft/snapshot. No token is stored on the node.
#
# Safe to run at any time, even while the bootstrap is still busy: the login only
# works once Vault holds real data (that's where the raft-snapshot auth role lives),
# so an uninitialised, empty or throwaway Vault can never be uploaded.

# node.env is generated by Terraform and only exists on the node.
# shellcheck disable=SC1091
set -euo pipefail
set -a; . /etc/vault-node/node.env; set +a
REASON=${1:-manual}

SNAP=$(mktemp /var/tmp/vault-XXXXXX.snap)
trap 'rm -f "$SNAP"; [ -n "${VAULT_TOKEN:-}" ] && vault token revoke -self >/dev/null 2>&1 || true' EXIT

VAULT_TOKEN=$(vault login -method=aws -token-only role=raft-snapshot)
export VAULT_TOKEN
vault operator raft snapshot save "$SNAP"

VERSION_ID=$(aws s3api put-object --bucket "$SNAPSHOT_BUCKET" --key "$SNAPSHOT_OBJECT_KEY" --body "$SNAP" \
  --metadata "reason=$REASON,instance-id=$(cloud-init query ds.meta_data.instance_id),vault-version=$(vault version | awk '{print $2}')" \
  --query VersionId --output text)   # awk: just the version, e.g. v2.1.1
echo "Snapshot ($REASON, $(stat -c %s "$SNAP") bytes) uploaded as s3://$SNAPSHOT_BUCKET/$SNAPSHOT_OBJECT_KEY version $VERSION_ID"
