#!/bin/bash
# usage: VAULT_TOKEN=<root token> vault-restore.sh
# Restore the latest snapshot in S3 over the running Vault: a rollback.
#
# Run by scripts/vault-ops.sh restore, which first saves the current state and then
# makes the chosen version the latest one ("promote"), so this node only ever needs
# to read the latest snapshot.

# node.env is generated by Terraform and only exists on the node.
# shellcheck disable=SC1091
set -euo pipefail
set -a; . /etc/vault-node/node.env; set +a
: "${VAULT_TOKEN:?VAULT_TOKEN must be set (root token)}"

snap=$(mktemp /var/tmp/vault-restore-XXXXXX.snap)
trap 'rm -f "$snap"' EXIT
version_id=$(aws s3api get-object --bucket "$SNAPSHOT_BUCKET" --key "$SNAPSHOT_OBJECT_KEY" "$snap" \
  --query VersionId --output text)
echo "Restoring s3://$SNAPSHOT_BUCKET/$SNAPSHOT_OBJECT_KEY version $version_id"
vault operator raft snapshot restore -force "$snap"

for _ in $(seq 60); do
  vault status >/dev/null 2>&1 && { echo "Vault restored from snapshot $version_id"; exit 0; }
  sleep 2
done
echo "ERROR: Vault did not come back unsealed after the restore." >&2
exit 1
