#!/bin/bash
# Bring Vault to a usable state on first boot: keep existing data, restore the
# latest snapshot onto an empty data volume, or initialise a new Vault and store
# its init output (root token + recovery keys).
#
# Idempotent: safe to re-run; an initialised Vault is left alone.
# The decision is at the bottom (case $STATE); each outcome is one function.

# node.env is generated by Terraform and only exists on the node.
# shellcheck disable=SC1091
set -euo pipefail
set -a; . /etc/vault-node/node.env; set +a

# Store-specific commands, generated by Terraform (Secrets Manager or Parameter Store).
STORE_INIT=/usr/local/libexec/vault-node/store-init     # init JSON on stdin
STORE_CHECK=/usr/local/libexec/vault-node/store-check   # exit 0 = a node already stored output
ALLOW_NEW=/etc/vault.d/allow-new-vault                  # one-shot override for refuse()

# IAM changes can take a little while to reach a freshly booted node.
retry() {
  for attempt in $(seq 10); do
    "$@" && return 0
    echo "$1 $2 failed (attempt $attempt), retrying..." >&2
    sleep $((attempt * 3))
  done
  return 1
}

wait_for_vault() {
  # `vault status` exits 0 = unsealed, 2 = sealed, 1 = error/unreachable.
  for _ in $(seq 60); do
    rc=0; vault status >/dev/null 2>&1 || rc=$?
    [ "$rc" -ne 1 ] && return 0
    sleep 2
  done
  echo "ERROR: Vault never became reachable." >&2
  return 1
}

# Prints one of:
#   initialised     Vault has data (this volume came from a previous node)
#   empty,snapshot  empty Vault, and a snapshot exists in S3
#   empty,stored    empty Vault, no snapshot, but a node already stored init output
#   empty,unknown   same, but the store couldn't be checked
#   empty           empty Vault, no snapshot, nothing stored: a brand-new deployment
#
# Runs in $(...), where set -e doesn't apply: every failure is handled explicitly
# (return 1 makes the assignment in the main flow fail, which stops the script).
# Guessing "empty" here would initialise a new Vault over existing data.
vault_state() {
  local initialized latest rc
  initialized=$(vault status -format=json | jq -r .initialized) || true   # exit code 2 = sealed
  case $initialized in
    true)  echo initialised; return ;;
    false) ;;
    *)     echo "ERROR: can't read Vault's status" >&2; return 1 ;;
  esac
  latest=$(retry aws s3api list-objects-v2 --bucket "$SNAPSHOT_BUCKET" --prefix "$SNAPSHOT_OBJECT_KEY" \
    --query 'Contents[0].Key' --output text) ||
    { echo "ERROR: can't check s3://$SNAPSHOT_BUCKET for snapshots" >&2; return 1; }
  if [ "$latest" = "$SNAPSHOT_OBJECT_KEY" ]; then
    echo empty,snapshot; return
  fi
  for attempt in $(seq 10); do
    rc=0; "$STORE_CHECK" >/dev/null || rc=$?
    case $rc in
      0) echo empty,stored; return ;;
      1) echo empty; return ;;
    esac
    echo "Checking $STORE_NAME failed (attempt $attempt), retrying..." >&2
    sleep $((attempt * 3))
  done
  echo empty,unknown
}

# A new volume (other availability zone, lost or replaced volume) must not become
# a new, empty Vault. Restoring needs an initialised Vault and a token, so
# initialise a throwaway one first. Its root token and recovery key are never
# stored: the restore replaces them with the originals from the snapshot, and the
# same KMS key unseals the restored data.
restore_latest() {
  local snap=/var/tmp/vault-restore.snap version_id
  version_id=$(retry aws s3api get-object --bucket "$SNAPSHOT_BUCKET" --key "$SNAPSHOT_OBJECT_KEY" "$snap" \
    --query VersionId --output text)
  echo "Empty Vault, restoring s3://$SNAPSHOT_BUCKET/$SNAPSHOT_OBJECT_KEY version $version_id"
  if ! VAULT_TOKEN=$(vault operator init -format=json -recovery-shares=1 -recovery-threshold=1 | jq -r .root_token) \
       vault operator raft snapshot restore -force "$snap"; then
    # Don't leave the throwaway (initialised, empty) Vault running as if it were real.
    systemctl stop vault
    echo "ERROR: restore failed; Vault stopped. To retry on this node:" >&2
    echo "  sudo sh -c 'rm -rf /opt/vault/data/* && systemctl start vault && /usr/local/bin/vault-bootstrap.sh'" >&2
    return 1
  fi
  rm -f "$snap"
  for _ in $(seq 60); do
    vault status >/dev/null 2>&1 && { echo "Vault restored from snapshot $version_id"; return 0; }
    sleep 2
  done
  echo "ERROR: Vault did not come back unsealed after the restore." >&2
  return 1
}

init_and_store() {
  local init
  # The init output only lives in this variable until it is stored.
  init=$(vault operator init -format=json -recovery-shares=3 -recovery-threshold=2)
  # Not retry(): each attempt needs the init JSON on stdin again.
  for attempt in $(seq 10); do
    if "$STORE_INIT" <<<"$init" >/dev/null; then
      echo "Vault initialised, init output stored in $STORE_NAME"
      rm -f "$ALLOW_NEW"
      VAULT_TOKEN=$(jq -r .root_token <<<"$init") /usr/local/bin/vault-configure-snapshots.sh
      return
    fi
    echo "Storing init output failed (attempt $attempt), retrying..." >&2
    sleep $((attempt * 3))
  done
  # The init output must never end up on disk, so don't keep it: this is a brand-new,
  # empty Vault (no data, no snapshot auth, so no snapshot of it either), and throwing
  # it away loses nothing. A re-run after fixing the cause initialises again.
  unset init
  systemctl stop vault
  rm -rf /opt/vault/data/*
  cat >&2 <<EOF
ERROR: could not store the init output in $STORE_NAME. Discarded this new, empty Vault
  (Vault stopped, /opt/vault/data wiped); its root token and recovery keys are gone.
  Fix the cause (usually the node's IAM permission to write $STORE_NAME), then:
    sudo systemctl start vault && sudo /usr/local/bin/vault-bootstrap.sh
EOF
  return 1
}

refuse() {
  cat >&2 <<EOF
ERROR: Refusing to initialise a new, empty Vault.
  The data volume is empty and there is no snapshot in s3://$SNAPSHOT_BUCKET/$SNAPSHOT_OBJECT_KEY,
  but $STORE_NAME already holds init output from an earlier node (or couldn't be checked).
  Initialising would overwrite that root token and those recovery keys.
Likely causes:
  - snapshots were silently failing, and the data volume was then lost or replaced
  - the secret outlived the snapshot bucket (restored after a destroy, or a recreated data layer)
  - the snapshots were deleted by hand
  - an earlier init's store write looked failed but went through (that Vault was discarded)
Options:
  - get the data back (a volume, or a snapshot version: scripts/vault-ops.sh promote <version>),
    then re-run: sudo /usr/local/bin/vault-bootstrap.sh
  - start from scratch on purpose (the old init output stays in the store's version history):
    sudo touch $ALLOW_NEW && sudo /usr/local/bin/vault-bootstrap.sh
EOF
  return 1
}

wait_for_vault
STATE=$(vault_state)
echo "Vault state: $STATE"
case $STATE in
  initialised)    echo "Vault already initialised, nothing to do." ;;
  empty,snapshot) restore_latest ;;
  empty)          init_and_store ;;
  empty,stored | empty,unknown)
    if [ -e "$ALLOW_NEW" ]; then init_and_store; else refuse; fi ;;
esac

# Only reached on success (set -e). vault-ops.sh wait-ready waits for this marker, so
# a node that refused or failed never counts as ready, and one repaired by hand
# (re-running this script) does, even though cloud-init still reports the failure.
mkdir -p /var/lib/vault-node
date -u +%FT%TZ > /var/lib/vault-node/bootstrap-done
