#!/bin/bash
# usage: VAULT_TOKEN=<root token> vault-configure-snapshots.sh
# Let this node's IAM role take Raft snapshots, and nothing else. Idempotent.
#
# The bootstrap runs this once with the fresh root token. Run it again to repair
# snapshot auth, or to set it up on a Vault that was initialised without it
# (scripts/vault-ops.sh configure-snapshots). It's stored in Vault's data, so it
# survives node replacement and snapshot restores.

# node.env is generated by Terraform and only exists on the node.
# shellcheck disable=SC1091
set -euo pipefail
set -a; . /etc/vault-node/node.env; set +a
: "${VAULT_TOKEN:?VAULT_TOKEN must be set (root token)}"

vault policy write raft-snapshot - <<<'path "sys/storage/raft/snapshot" { capabilities = ["read"] }'

# jq -e: exit code says whether the aws/ auth mount already exists
vault auth list -format=json | jq -e 'has("aws/")' >/dev/null || vault auth enable aws

# resolve_aws_unique_ids=false: match on the role ARN only, so a recreated role
# with the same name still works (it would otherwise need iam:GetRole too).
vault write auth/aws/role/raft-snapshot auth_type=iam \
  bound_iam_principal_arn="$ROLE_ARN" resolve_aws_unique_ids=false \
  token_policies=raft-snapshot token_ttl=10m token_max_ttl=10m

echo "Snapshot auth configured for $ROLE_ARN"
